### ISSUE TITLE
請問是否可提供更多詳細的操作內容?

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#1]
你好，請問是否可提供更詳細的內容，
例如python之外，還需要安裝那些包，
該如何用指令來下載、該如何登入自己的帳號等，
感謝!

**Comment by Diaoxiaozhang** [comment]
抱歉，这个项目还没有制作完，但是大概一个礼拜以内命令行版的应该就能制作完了，GUI还得再等等。我到时候发布的release应该会是傻瓜式的exe，不需要安装任何包。

**Comment by c469591** [comment]
了解，十分感謝!
