### ISSUE TITLE
可以单独出一个XM文件解密能吗

### ISSUE THREAD

**Issue by q2514** [Diaoxiaozhang/Ximalaya-Downloader#12]
可以单独出一个XM文件解密功能吗

**Comment by Diaoxiaozhang** [comment]
抱歉哈，这个软件的原理是从喜马拉雅的网页版音频播放接口直接爬取音频，不是解密xm文件，xm文件如何解密我也不清楚

**Comment by q2514** [comment]
这里有个解密教程，不知道有没有用：
https://www.aynakeya.com/2023/03/15/ctf/xi-ma-la-ya-xm-wen-jian-jie-mi-ni-xiang-fen-xi/

**Comment by q2514** [comment]
> 抱歉哈，这个软件的原理是从喜马拉雅的网页版音频播放接口直接爬取音频，不是解密xm文件，xm文件如何解密我也不清楚

这里有个解密教程，可以看看有没有用，我看不懂 ~_~！
https://www.aynakeya.com/2023/03/15/ctf/xi-ma-la-ya-xm-wen-jian-jie-mi-ni-xiang-fen-xi/

**Comment by Diaoxiaozhang** [comment]
我研究一下吧

**Comment by Diaoxiaozhang** [comment]
我明后天单独搞一个repo用于实现这个功能，等以后这个程序我做出gui了我会把功能整合到里面来

**Comment by Diaoxiaozhang** [comment]
xm解密做出来了，https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt，可以看一下

**Comment by Diaoxiaozhang** [comment]
xm解密做出来了，https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt ，可以看一下
