### ISSUE TITLE
下載部分聲音只能從第一個曲目開始

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#13]
你好，剛剛發現下載部分聲音的功能有bug，
我有一個專輯有一千多級，1-500沒問題，但501-1000下載完成後，發現雖然文件名開頭的數字是隊的，但標題仍然是從第一級開始
另外能否控制文件名是否要有編號? 發現有些專輯自己有編號，有時候可能兩者布疋配，
感謝!

**Comment by Diaoxiaozhang** [comment]
请提供日志

**Comment by c469591** [comment]
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11328016/app.log)

**Comment by Diaoxiaozhang** [comment]
你发的日志貌似是个空文件，能否再复现一遍这个错误然后把日志发过来？每次重新运行日志都会清空的

**Comment by Diaoxiaozhang** [comment]
控制是否加编号我会在下个版本加入的

**Comment by c469591** [comment]
測試了好多次，用6版跟5版，使用下載部分聲音，雖然都會產生日誌文件，但日誌文件裡面都是空的

**Comment by Diaoxiaozhang** [comment]
你确定是成功下载了音频吗？只要是调用了下载音频的函数不太可能没有日志，或者你看看下载完先不关闭程序有没有日志

**Comment by c469591** [comment]
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11339452/app.log)
可以了

**Comment by Diaoxiaozhang** [comment]
你这个是到了vip音频下载上限了，明天再试吧

**Comment by c469591** [comment]
剛剛試過，直接使用下載部分聲音還是無法產生日至，exe沒有關閉的情況下打開日誌也是空的，
只能先下載全部聲音，之後再用下載部分聲音的功能才會有日誌內容

**Comment by c469591** [comment]
嘗試下載免費專輯後發現軟件會閃退，有成功生成日至
[下載全部聲音 免費專輯直接閃退.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11349053/default.log)

**Comment by c469591** [comment]
剛又測試了好幾輪，找了比較少曲目的專輯直接下載全部聲音也無法產生日至，
也找了其他不同的專輯下載部分聲音，無論範圍輸入多少，他都會從第一集開始下載，
例如我打501 503 ，下載回來後文件名編號是對的，但標題其實是第一級到第三集的標題，
請問作者本地測試是正常的嗎?

**Comment by Diaoxiaozhang** [comment]
我这里测试一直是正常的，而且理论上来说只要成功调用下载音频的函数，就一定会生成日志。而且我看你发过来成功生成的日志也是有问题的，我也不太清楚为什么。我今天晚上去设置一下日志文件的编码格式，看看会不会是这个原因。至于你没法下载音频的原因，感觉还是和ip有关系。我回头再写个测试程序你运行一下我看看到底是什么问题。

**Comment by c469591** [comment]
好的感謝，那就等你的測試版

**Comment by Diaoxiaozhang** [comment]
我做了一个xm解密的程序，https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt ，可以看一下。如果Ximalaya-Downloader你用着还是有问题可以试试用喜马拉雅客户端下载xm文件然后解密。

**Comment by c469591** [comment]
非常感謝，
但我還是覺得現在這個工具比較符合我的需求，
還要再另外弄喜馬客戶端下載在解密說真的會變的很不方便

**Comment by Diaoxiaozhang** [comment]
这个解密xm的工具我也只是因为看到有人发的issue说有需求需求然后就照着另一个大佬的教程做的，我主要还是做这个Ximalaya-Downloader，准备等过段时间做个gui然后把功能整合到一起

**Comment by c469591** [comment]
了解，期待更新!!

**Comment by Diaoxiaozhang** [comment]
我更新了，你试试看最新版的能不能正常生成日志吧

**Comment by c469591** [comment]
有了!
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11358782/app.log)

**Comment by c469591** [comment]
另外這個是下載免費聲音直接閃退的日治
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11358785/app.log)

**Comment by Diaoxiaozhang** [comment]
你是下载所有的整个的专辑都会闪退吗？

**Comment by Diaoxiaozhang** [comment]
最好能找找规律看看具体什么样的情况下会出现这样的错误，因为我实在是无法复现这个错误

**Comment by Diaoxiaozhang** [comment]
我拿香港的节点测试了一下，发现也出现这个问题了，看来是ip问题，我研究一下解决方法

**Comment by c469591** [comment]
我是下載整張專輯就閃退，免費的才會，
vip的可以正常下載，
感謝，辛苦你了!

**Comment by Diaoxiaozhang** [comment]
你试试看新版本能不能正常用吧，如果显示解析专辑失败就多试几遍

**Comment by c469591** [comment]
下載免費專輯，選擇全部下載仍然閃退，嘗試了四五次，這是日治→
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11360493/app.log)

**Comment by Diaoxiaozhang** [comment]
已找到原因，下个版本会修复

**Comment by c469591** [comment]
感謝!
另外發現下載部分聲音完成後，選項仍然停留在下載整個專輯或下載部分聲音，不會回到初始選項，
是否能在每一次的選項中加入一個選項，可以返回最開始的選項菜單，例如
0 返回主選項
另外，我還發現一個帳號一天可以成功下載1000集

**Comment by Diaoxiaozhang** [comment]
新版本已发布，这次应该是可以了

**Comment by c469591** [comment]
不會崩潰了，但沒下載成功，日至→
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11361496/app.log)

**Comment by Diaoxiaozhang** [comment]
不太应该啊🤔你账号正常登陆了吗

**Comment by Diaoxiaozhang** [comment]
这样，你把这个压缩包里的程序放到Ximalaya-Downloader同目录下，然后运行一下，把日志发过来，我看看是什么问题
[test.zip](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11361522/test.zip)

**Comment by c469591** [comment]
我直接運行剛剛你發的exe，只有一行，我就直接貼過來了
2023-04-30 22:30:52,913 - DEBUG - {'reqId': '6b024598-170073263', 'ret': 927, 'msg': '很抱歉，由于版权方要求，您所在的地区/国家暂时无法使用该资源', 'extendInfo': {'isDownHimalayaApp': False, 'currentPositionFrom': 2, 'msg': '应版权方要求，该资源仅限中国大陆用户使用,若你当前位于中国大陆,请点击此处允许我们<location>获取你的准确位置</location>', 'pageStyle': 'old'}}

**Comment by Diaoxiaozhang** [comment]
你如果成功登录账号了应该不会这样的吧，你下载vip音频是正常的吗？

**Comment by c469591** [comment]
對，下載是正常的，是直接執行
test.exe
ˇ對吧?

**Comment by Diaoxiaozhang** [comment]
可能是cookie问题？你要不试试把config文件删了重新登录一下

**Comment by c469591** [comment]
我患了我朋友的
config.json
出現不一樣的結果了
他是大陸購買的會員帳號
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11361538/app.log)

**Comment by Diaoxiaozhang** [comment]
这样的话是能够正常下载的，难道不同地区的账号也是有区别的吗，我也不太清楚啊😂

**Comment by Diaoxiaozhang** [comment]
我反正用大陆的账号，香港的ip是能够正常下载的。我也没有香港的账号，不太了解，你平时在ximalaya.com上能够正常听音频吗？还是要用国际版客户端啊

**Comment by c469591** [comment]
還甄別說，我喚他的
config.json
可以順利下載免費專輯了，真是醉了
平常我用自己的帳號，搭配iphone是可以順利聽上面的音頻，我用的不是國際板

**Comment by c469591** [comment]
不過這樣總比認IP好，不然大家只會翻出來，要翻進去我可就抓瞎了

**Comment by c469591** [comment]
另外免費專輯是無法選擇因值得嗎?
下載免費專輯沒有選擇因值的選項

**Comment by Diaoxiaozhang** [comment]
应该是无法选择音质的

**Comment by Diaoxiaozhang** [comment]
我测试下来网页版的接口是无法选择音质的，但是客户端的应该可以，我再研究研究看看能不能调用客户端的接口

**Comment by Diaoxiaozhang** [comment]
我又去研究了一下，发现是之前搞错了，有的音频没有高音质只有普通音质，我误以为免费音频没有高音质了😂，下个版本会给有高音质的声音加入高音质选项的

**Comment by c469591** [comment]
好得好的，感謝
