### ISSUE TITLE
VIP资源每个帐号一天限制了1000个下载，超过会失败，提两个解决方向建议。

### ISSUE THREAD

**Issue by q2514** [Diaoxiaozhang/Ximalaya-Downloader#14]
方向一：配置文件加入多个帐号切换的功能，1000的额度用完了，自动切换帐号，这个感觉限制还是很明显，毕竟很少人会有几个VIP帐号。

方向二（推荐）：官方客户端下载好像没有1000个的限制，可以通过客户端下载xm文件，然后进行解密。
这里会涉及一个文件名还原的问题，下载下来的文件名都是转码过的，一个个手动改名恢复会很麻烦。所以解密完之后最好加入文件名还原成软件里看到的文件名的功能。
关于文件名还原，看下这个教程有没有参考价值：https://note.youdao.com/ynoteshare/index.html?id=6b7a9cf902907d4dc4fb97c394a5918e&type=note&_time=1682336799029

**Comment by Diaoxiaozhang** [comment]
xm文件解密我在另一个repo里在做了，做完会发出来的，再过段时间我做个gui出来把各个功能整合到一起

**Comment by Diaoxiaozhang** [comment]
xm解密做出来了，https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt ，可以看一下
