### ISSUE TITLE
非常好用！但能否加一个自动转mp3的选项呢

### ISSUE THREAD

**Issue by jia58960** [Diaoxiaozhang/Ximalaya-Downloader#15]

**Comment by Diaoxiaozhang** [comment]
感觉没有这个必要吧，99%的音频播放器都是支持m4a的吧。要是实在想要转格式就用格式工厂吧，在这个程序里加个转mp3的功能感觉有点鸡肋了。

**Comment by cf020031308** [comment]
可以用ffmpeg转：`for f in *.m4a; do ffmpeg -i "$f" -acodec libmp3lame -vn -b:a 320k "${f%.m4a}.mp3"; done`
