### ISSUE TITLE
下載部分專輯時輸入的範圍超過專輯聲音時會導致崩潰

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#16]
你好，
我發現當輸入下載部分聲音時，如果輸入的範圍大魚專輯最大聲音時，軟件會直接崩潰，
例如專輯只有1000，而我輸入了999 1001，軟件就會崩潰，
謝謝!
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11406647/app.log)

**Comment by Diaoxiaozhang** [comment]
知道了，我现在正好在重构代码，估计要几天
