### ISSUE TITLE
关于解密的问题

### ISSUE THREAD

**Issue by fu9809** [Diaoxiaozhang/Ximalaya-Downloader#22]
首先，对大佬表示真诚的感谢，这个解密url和解密xm文件的方法很强。

如果您有时间，可以发一篇文章，或者一个视频，说明一下您是如何破解它加密步骤，并进行解密的吗？

小白一枚，感觉这些东西很强大，想学习一下，如果您有解密相关的学习路线，希望您也能分享一下~

万分感谢！

**Comment by Diaoxiaozhang** [comment]
网页版下载接口的解密其实就是js逆向，你在网上搜搜教程很多的，至于xm解密你可以看看ximalaya-xm-decrypt的readme，我是参考了一个别的大佬的文章
