### ISSUE TITLE
无法通过浏览器登录

### ISSUE THREAD

**Issue by xiaowenlv** [Diaoxiaozhang/Ximalaya-Downloader#26]
选择浏览器登录就直接闪退了，两个浏览器都一样，能否使用默认浏览器或者手动指定浏览器。

**Comment by Diaoxiaozhang** [comment]
抱歉哈，是新版本的bug，可以先用0.2版本，我这两天有空修一下

**Comment by Diaoxiaozhang** [comment]
已修复，是selenium版本的问题

**Comment by xiaowenlv** [comment]
> 已修复，是selenium版本的问题

只能用原版的chrome吗，报错了，绿色版或者修改版是不是不能用。
selenium.common.exceptions.Web Driver Exception：Message：unknown error：can not find Chrome binary
selenium.common.exceptions.Web Driver Exception：Message：unknown error：Failed to create Microsoft Edge process.

**Comment by Diaoxiaozhang** [comment]
确实是只能用原版，绿色版的话得自己配置selenium的option，你要么装一个原版的，要么就手动获取cookie填到config里
