### ISSUE TITLE
下载专辑声音失败

### ISSUE THREAD

**Issue by qch1933** [Diaoxiaozhang/Ximalaya-Downloader#33]
The below is error output when run. 

while I use  below link to get specific soud, it has response. 
https://www.ximalaya.com/mobile-playpage/track/v3/baseInfo/1706705279276?device=web&trackId=64429939&trackQualityLevel=2

Ximalaya-Downloader-main/cli.py:11: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
欢迎使用喜马拉雅下载器
在config文件中未检测到有效的下载路径，将使用默认下载路径，如果想要修改下载路径，请修改config.json文件中的path字段为你想要的下载路径
未检测到有效喜马拉雅登录信息，请2选择是否要登录：
1. 登录
2. 不登录
2
请选择要使用的功能：
1. 下载单个声音
2. 下载专辑声音
3. 退出程序
2
请输入专辑ID或链接：
12285737
成功解析免费专辑12285737，专辑名Trials of Apollo-Rick Riordan，共58个声音
请选择要使用的功能：
1. 下载整个专辑
2. 下载专辑的部分声音
3. 显示专辑内声音列表
1
请选择是否要在下载的音频文件名中加入序号：
1. 加入序号
2. 不加序号
2
请选择您想要下载的音质：（直接回车默认为普通音质）
0. 低音质
1. 普通音质
2. 高音质（如果没有高音质则将下载普通音质）
1

ID为64429939的声音解析失败！

ID为86721652的声音解析失败！

ID为86721626的声音解析失败！

ID为86721620的声音解析失败！

ID为86721658的声音解析失败！

ID为251110561的声音解析失败！

ID为86721645的声音解析失败！

ID为86721664的声音解析失败！

ID为86721650的声音解析失败！

ID为86721649的声音解析失败！

ID为86721659的声音解析失败！

ID为86721630的声音解析失败！

ID为86721618的声音解析失败！

ID为86721654的声音解析失败！

ID为86721629的声音解析失败！

ID为86721622的声音解析失败！

ID为343611263的声音解析失败！

ID为86721656的声音解析失败！

ID为86721660的声音解析失败！

ID为86721648的声音解析失败！

ID为86721646的声音解析失败！

ID为86721662的声音解析失败！

ID为86721638的声音解析失败！

ID为86721633的声音解析失败！

ID为86721644的声音解析失败！

ID为86721635的声音解析失败！

ID为64429938的声音解析失败！

ID为86721623的声音解析失败！

ID为64439295的声音解析失败！

ID为251110562的声音解析失败！

ID为64439294的声音解析失败！

ID为86721625的声音解析失败！

ID为86721640的声音解析失败！

ID为86721651的声音解析失败！

ID为86721636的声音解析失败！

ID为86721657的声音解析失败！

ID为86721643的声音解析失败！

ID为86721627的声音解析失败！

ID为86721663的声音解析失败！

ID为343608351的声音解析失败！

ID为86721637的声音解析失败！

ID为86721632的声音解析失败！

ID为251110563的声音解析失败！

ID为86721616的声音解析失败！

ID为86721619的声音解析失败！

ID为86721634的声音解析失败！

ID为86721639的声音解析失败！

ID为86721661的声音解析失败！

ID为86721665的声音解析失败！

ID为86721642的声音解析失败！

ID为86721647的声音解析失败！

ID为86721621的声音解析失败！

ID为86721653的声音解析失败！

ID为86721641的声音解析失败！

ID为343612747的声音解析失败！

ID为86721628的声音解析失败！

ID为86721631的声音解析失败！

ID为86721655的声音解析失败！
Traceback (most recent call last):
  File "/Users/hob_yu/Backup/PythonScripts/ximalay/github/Ximalaya-Downloader-main/cli.py", line 184, in <module>
    loop.run_until_complete(ximalaya.get_selected_sounds(sounds, album_name, start, end, headers, int(choice), number, path))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/hob_yu/Backup/PythonScripts/ximalay/github/Ximalaya-Downloader-main/main.py", line 256, in get_selected_sounds
    await asyncio.wait(tasks)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 368, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x102ef4e20>

**Comment by Diaoxiaozhang** [comment]
Please send me the log file so I can know exactly what went wrong, btw are you in Chinese mainland or not? IP location may affect downloading.

**Comment by qch1933** [comment]
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/14121541/app.log)
请看log, 选择下载专辑声音失败
我是大陆人，用的国内地址
选择不登录，下载单个声音没有问题

**Comment by Diaoxiaozhang** [comment]
你把第124行和第206行的session.get方法加上ssl=False参数试试

**Comment by qch1933** [comment]
session.get方法加上ssl=False就能下载。
