### ISSUE TITLE
下载过来好多空的，导致整个专辑杂乱无序，Ximalaya-XM-Decrypt解密建议给个大概效果视频，既然官方vip只给1000个,能不能设置按顺序下载前1000，比如输入200-1200，只下载1000个

### ISSUE THREAD

**Issue by b410146464** [Diaoxiaozhang/Ximalaya-Downloader#35]

**Comment by Diaoxiaozhang** [comment]
请描述清楚，最后配上日志文件和图片，下载下来空的，杂乱无序是什么意思？空是指文件内容为空还是什么，杂乱无序是序号标记功能出问题还是什么。下载上限是一天总的上限，不是单此下载上限，我没法知道你下载的时候离上限还有多少，所以没法在程序里控制，只能你自己下载的时候控制一下量

**Comment by Diaoxiaozhang** [comment]
xm-decrypt还是很简单的吧，在喜马拉雅客户端下载好xm文件，然后打开xm-decrypt，它会有引导的
