### ISSUE TITLE
下载整个专辑，内容很多无效，只读取了名称，没有音频内容，V0.3.3版本

### ISSUE THREAD

**Issue by b410146464** [Diaoxiaozhang/Ximalaya-Downloader#36]
问题一、也是最大问题
比如圣墟需要VIP来下载，一共2379个声音文件，但是只有1786个是有效的，另外的600个都是无效的，读取了名称，没有内容。比如圣墟 第762集听完，763有，但是都是没有内容的，这种有600个，掺杂在各个序列，有在几十集的残缺，1百多集的残缺，杂乱无章。整个专辑就没有连续性了，作用大打折扣。
![Snipaste_2024-02-10_15-00-09](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/159541801/5df82a2d-626e-4b53-b865-32abac23f798)

问题二、
能不能多出一个功能，
比如
4.下载专辑段号声音
输入专辑200-300，输入整个专辑ID，只下载200-300的声音
![Snipaste_2024-02-10_15-12-44](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/159541801/f3042a7b-dad2-4b99-9d0b-16df21f842ac)

**Comment by Diaoxiaozhang** [comment]
下载专辑内部分声音的功能是有的，你输入专辑信息后会有“下载部分声音”的选项，输入起始和结束的编号中间空格分开就行。下载下来是空文件的问题我没有遇到过，你复现问题后把日志发来看看，日志就是app.log，会自动生成。你今天应该到下载上限了，明天你可以试试下载部分音频，不要超过1000个，看看还会不会有这样的问题。

**Comment by b410146464** [comment]
测试过100个，没有出现这个问题，测试999个，大概出现106个有问题的
![Snipaste_2024-02-10_20-34-45](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/159541801/c6de9eff-d33b-4bb9-a7af-49b3cba7474a)

**Comment by b410146464** [comment]
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/14229258/app.log)
app.log

**Comment by Diaoxiaozhang** [comment]
你先试一下0.3.2版本，我估计是新版本的错误重试部分代码出bug了

**Comment by Diaoxiaozhang** [comment]
对了，你下载的时候是不是程序还没运行完就关掉了

**Comment by Diaoxiaozhang** [comment]
新版已修复，请测试
