### ISSUE TITLE
把0.3.4版本放到原来0.3.2版本的同一目录下，继续下载上次有空音频的专辑时，提示存在，没有重新下载

### ISSUE THREAD

**Issue by paradise321** [Diaoxiaozhang/Ximalaya-Downloader#37]
原来的download目录下面，有些音频大小为0字节，还是提示“……已存在！”，然后“专辑全部选定声音下载完成！”，需要先手工删除下大小为0的音频后再次重试。
除了检查文件名，建议还可以再加个文件大小判断，如果为0字节，则也重新下载。

**Comment by Diaoxiaozhang** [comment]
这个没啥必要吧，你按大小排序删一下就可以了，这个bug修了以后应该不会再出现这种情况

**Comment by Diaoxiaozhang** [comment]
我增加了多次重试下载结束后如果有下载失败下载了空文件会删掉的功能

**Comment by paradise321** [comment]
前一次专辑下载未完成，下一次继续下载同一专辑时，还是会出这样的问题，还得手工删除，软件可以设计得更好些😄
