### ISSUE TITLE
有几个建议想提出，烦请抽空观看

### ISSUE THREAD

**Issue by wei9133** [Diaoxiaozhang/Ximalaya-Downloader#38]
你好目前有几个问题
1.检测到当前ip不在中国大陆，由于喜马拉雅官方限制，必须登录才能继续使用
实际上免费的部份（就是试听的部份）与免费书应该可以在没有cookie的情况下载
至少油猴插件的脚本是可以做的，如果可以的话，这个部份麻烦考虑看看能否施做
https://greasyfork.org/zh-TW/scripts/435495  ← 这是油猴那个脚本

2.能否增加自行设定下载间隔时间，目前程式是直接暴力全数下载，可能有被封号的风险
能否让用户自行设定下载间隔。
例如︰下完一个档案之后间隔30秒才下载下一个档案
最理想的状态是让用户设定一个区间，而程式在这个区间内随机取一个数，倒数完之后才进行下一个档案下载
例如︰用户设定下载间隔为30秒至180秒，那就下完一个档案后随机等待30秒～180秒，再下下一个档案，然后再随机等待此区间秒数
循环往替。

3.希望增加设定proxy的功能
就如同贵程式一开始检测IP是否在中国大陆一样，某些书会有非中国大陆IP，无法下载的问题，就算有vip也没用
必须要挂上代理转为中国大陆IP才能够下载，而在chrome里可以直接对chrome挂代理，而不会影响到全局
目前贵程式如果想要下载此类书籍，我想到的只有改全局去套用代理才能够实现下载
故希望能够提供设定代理功能

4.这个是第三点的补充，是希望而非必要
能够提供批量测试喜玛拉雅站点代理是否能够使用的功能
网路上提供的免费中国porxy，很多都显示可以用，但实际上是连不上喜玛拉雅的
如果有个测试工具可以以xxx.xxx.xxx.xxx	xxxx (中间空格可为tab或:)
例如将下列proxy丢进程式里，由程式帮忙测试是否能够连接到喜玛拉雅
（就是测试本地IP挂上 proxy IP能否连上目标IP的程式）
14.103.24.20	8000
14.103.26.198	8000
223.215.177.206	8089
47.100.91.57	8080
121.46.201.241	80
121.230.208.226	7788
47.100.254.82	80
120.24.176.185	8080
106.14.255.124	80
60.12.168.114	9002
60.174.1.24	8089
114.231.82.137	8089
当然如果可以指定到页面是最好，直接相当于多出一个由自己所在地去测试
自己是否能够连上代理伺服器，并连接到需要用的网页的测试程式

以上几点，麻烦参考看看，谢谢

**Comment by Diaoxiaozhang** [comment]
关于暴力下载导致封号的问题大可以放心，这个程序发布到现在超2000次的下载量还没有出现过封号的案例，只要不要超大量下载应该就不会有什么问题，正常下载一两个专辑基本没有封号风险，如果像你说的那样单线程下载且每两个音频下载之间等待几十秒效率未免过低了些。至于ip不在中国大陆的下载问题，经过我的测试，大多数音频在非大陆ip且未登录情况下都是不能下载的，用了你说的脚本也不行，你可以看看[issue#13](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/issues/13)，里面就是一个台湾朋友遇到这个问题，然后我才在程序中设定非大陆ip必须登录才能使用。至于ip代理，网上寻找到的免费ip代理往往要么无效，要么速度极慢，想要能够稳定下载几m大小的音频文件肯定是需要使用付费ip代理的，等我有空我在研究一下使用ip代理的可行性。

**Comment by wei9133** [comment]
你好，当初实际上可在未登录状态用来下载免费书的脚本是chrome的扩充功能
而且要用开发者模式去加载未封装的项目
不过重装之后就无法使用了(我最后一次正常使用是在2023/12/03)
会回报
"Manifest version 2 is deprecated, and support will be removed in 2024.
 See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details."
东西如附件，有兴趣的话可以参考看看，没兴趣就算了
这个可以PASS，在有疑虑的情况下，多注册一个号分摊单日下载数量应该可行

挂代理的部分还请你抽空评估可行性

另外有一点，因程序默认要获取cookie与下载专辑用的是专辑ID或链接
那我假设所有用户都是用浏览器去查找自己要的书
但网页版是看不到这个专辑是版权限制的(例如：ID 55817225 & ID 68557304)
在app里面是会显示，版权限制，所在地区暂时无法购买
若碰到无法下载的部分，程序是否会通知"版权限制，所在地区无法下载呢?"
会的话可能会较方便用户知道要去挂上代理後才能够下载

我当前没有VIP帐号去测，若程序已有该功能请无视这条

感谢你的回复

[喜马拉雅最新下载工具V4.zip](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/14438647/V4.zip)
