### ISSUE TITLE
關於使用的問題和建議

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#4]
你好，這個軟件非常適合我用，但我遇到一些問題，整理如下→

1. 我用威信或是qq登入，但回到cmd介面之後，他仍然較我輸入cookie，
因此我直接按enter跳過該步驟，直接輸入網址來下載，
輸入的網址都是vip會員才能收聽的網址，
但輸入專輯往只能解析出曲目的名稱，卻都顯示無法下載，
輸入某一個曲目的網址，他會顯示解析失敗
專輯往只是
https://www.ximalaya.com/album/22365086
請問是必須用手機號登入才行嗎?
1. 請問下載回的文件是最高音質嗎?
1. 希望可以自訂下載的保存位置
1. 另外gui的開發希望可以讓視障朋友也能操作，
windows10+的系統可以按ctrl+win+enter打開講述人來測試，
基本上按tab鍵都能朗讀、上、下、左、右鍵能操控並朗讀gui就ok了
1. 我會將這個好用工具分享到我的網站，把好用的工具分享給更多人→
[小羔羊分享站](https://lamb.tw/)

非常感謝作者的辛苦付出!

**Comment by c469591** [comment]
剛剛嘗試下載免費專輯，清除紀錄文件後選擇不登入，選擇下載整個專輯之後會導致閃退，
往只是
https://www.ximalaya.com/album/62264572

**Comment by c469591** [comment]
找了使用檢體系統的朋友測試，他那裏目前可以下載免費專輯，但付費專輯一樣下載失敗，
但我用我電腦，以及用Vmware虛擬機下載免費專輯測試都會閃退，
兩個系統都是繁體系統

**Comment by Diaoxiaozhang** [comment]
非常感谢你的反馈！但是经过我这边的测试，不管是使用微信还是qq登录都是正常的，下载免费与付费的专辑也都是正常的。最近我会再写一个能够生成日志文件的版本，请你使用它测试然后将日志文件发给我以便我了解到底是为什么出错。自定义保存位置我会在下个版本加入的，但是gui估计短时间内是完成不了的，我自己也没有gui的开发经验，还需要学习。最近我也有很多事情要忙，所以你的问题可能要花一些时间才能解决，希望能谅解！

**Comment by c469591** [comment]
好的，沒問題，如果推出了有日誌的版本在麻煩到這裡留言一下，我收到mail後馬上來測試，
非常感謝!

**Comment by Diaoxiaozhang** [comment]
你好，最新的release已经包含了生成日志的功能，麻烦你再测试一下，发生错误就把日志发在这个issue里。另外，关于你登录账号的问题，我想问一下，你登陆完后config文件里有获取到的cookie吗？

**Comment by Diaoxiaozhang** [comment]
还有就是你和你朋友都是使用非大陆ip测试的吗？因为我发现我使用的喜马拉雅的api好像对非大陆ip有限制

**Comment by c469591** [comment]
我朋友是使用大陸ip，他在上海，但他是使用威信登入，我讓他發二為馬讓我掃馬登入，
但他一樣沒辦法下載vip專輯，免費專輯卻可以下載，
我自己是非大陸ip，日誌如下
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11223297/app.log)

**Comment by Diaoxiaozhang** [comment]
好的收到，但是最近比较忙，这个问题可能还要过几天才能解决。

**Comment by c469591** [comment]
你好，今天看到更新，使用後發現可以下載了，但好像有幾級失敗了，看cmd有一些抱錯訊息，
似乎有些沒有下載成功，但一千多級，不知道如何看那些是下載失敗，
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11257300/app.log)
希望可以將下載失敗的曲目名稱輸出到另一個檔案方便查閱，下面是日治，感謝!

**Comment by Diaoxiaozhang** [comment]
这个情况是达到每天能够下载的付费声音的上限了，这个问题我暂时还没解决，另外过两天我会针对下载失败的处理进行优化的
