### ISSUE TITLE
是否能新增解析手機板連結的功能

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#41]
你好大大，最近發現下載工具無法解析手機板喜馬拉雅分享的連結，是否可以新增對這種連結的解析，
或是有什麼策略可以轉換手機板連結成電腦版的聯結呢
下面這是網址
https://m.ximalaya.com/selfshare/album/56206086?uid=140986368&shrdv=e8d4322a-2789-374f-983a-ab0054d0ead5&shrh5=android&shrid=18e2c16d427152fd&shrdh=1&shrpid=18e2c16d4277c33&srcType=6&subType=1010&srcId=56206086
最近一週都在研究此項目的code，解析的部分還沒研究，
要是大老有絲路可以先分享函數讓我來測試測試也行，感謝!

**Comment by Diaoxiaozhang** [comment]
手机版和电脑版的album id和sound id是一样的吧，改下正则就行，回头我搞一下
