### ISSUE TITLE
如何解決TypeError: argument of type 'ClientSession' is not iterable

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#42]
你好，最近發現有些專輯下載時會發生如標題的錯誤，這是報錯的最後幾行
  File "d:\python\魔鏡歌詞\code\Ximalaya_main.py", line 238, in async_get_sound
    album_name = self.replace_invalid_chars(album_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\魔鏡歌詞\code\Ximalaya_main.py", line 186, in replace_invalid_chars
    if char in name:
       ^^^^^^^^^^^^
TypeError: argument of type 'ClientSession' is not iterable
我下載的是這個網址
https://www.ximalaya.com/album/21824864
我也檢查了代碼，問題是出在replace_invalid_chars方法中，似乎送入了一個ClientSession參數給他導致的錯誤，
但是我查了其他掉用此方法的方法沒有看出問題在哪裡，搞不清楚為啥就送了個ClientSession進去，
我是選下載全部專輯的時候，大概到最後幾集的時候才報錯的，
在請大大看應該如何解決，感謝

**Comment by Diaoxiaozhang** [comment]
我在自己尝试下载这个专辑时发现了更多问题，有空我再解决吧，最近比较忙

**Comment by Diaoxiaozhang** [comment]
最新版已修复
