### ISSUE TITLE
是否可以支持下載無損格式

### ISSUE THREAD

**Issue by c469591** [Diaoxiaozhang/Ximalaya-Downloader#44]
你好，聽說喜馬拉雅最近有推出無損格式，但目前只有比較少的專輯才有，
請問是否可以支持下載無損格式的呢?
下面這個是有無損的專輯
https://www.ximalaya.com/album/38160002
謝謝

**Comment by Diaoxiaozhang** [comment]
我看了一下，这个专辑网页版貌似最高只支持64kbps，你是在哪里看到的支持无损格式？

**Comment by bai1an** [comment]
https://www.ximalaya.com/sound/232802662 这个在app可以看到无损音质

**Comment by Diaoxiaozhang** [comment]
> https://www.ximalaya.com/sound/232802662 这个在app可以看到无损音质

测试了一下，手机app确实有无损且可以收听，但电脑客户端虽然有显示但好像无法切换至无损并收听，网页版链接我抓包出来发现应该还没有无损，所以现在应该还在测试阶段
