### ISSUE TITLE
喜马拉雅 APP 下载的大量文件 怎么 批量重命名

### ISSUE THREAD

**Issue by yonggedebaqi** [Diaoxiaozhang/Ximalaya-Downloader#46]
喜马拉雅 APP 下载的大量文件 怎么 批量重命名

**Comment by Diaoxiaozhang** [comment]
简单的python脚本即可实现，网上也有现成的重命名工具，具体看你要怎么重命名，最方便的其实就是给chatgpt讲你的需求让它帮你写个python脚本

**Comment by yonggedebaqi** [comment]
喜马拉雅 APP 下载的缓存都是一些编码文件，怎样改回专辑列表中的文件名。

**Comment by Diaoxiaozhang** [comment]
手机版的啊，这个我不清楚
