### ISSUE TITLE
声音解析失败，可能因为达到每日付费音频下载上限

### ISSUE THREAD

**Issue by sof11911** [Diaoxiaozhang/Ximalaya-Downloader#55]
作者好，请问为什么我从来都没下载过任何付费音频，但一直有这个错误提示，导致从没成功下载过一个音频。非常感谢您
的付出和帮助！（目前人在国外）

![ly](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/168954252/620c18f1-3edf-4b4b-9f5b-e81614a559d6)
[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/15211983/app.log)

**Comment by Diaoxiaozhang** [comment]
1. 第二天再试试
2. 怀疑是程序对达到每日付费音频下载上限的判断不严谨，建议使用v0.3.4版本进行测试
3. 是否有登录账号再进行下载

**Comment by sof11911** [comment]
感谢回复，我就是从v0.3.4开始的，出现这个错误后以为新版本会解决，之后每个版本都有试过不止一次，都是同样结果。因为在国外，所以都有按要求登录。

**Comment by AnitaCanthus** [comment]
> 1. 第二天再试试
> 2. 怀疑是程序对达到每日付费音频下载上限的判断不严谨，建议使用v0.3.4版本进行测试
> 3. 是否有登录账号再进行下载

作者，你好，请求下载app端音频源，app端不限制下载上限

**Comment by wx5223** [comment]
同样的问题 最新的版本 下载不了了

**Comment by Diaoxiaozhang** [comment]
我自己测试了一下，在开启全局模式香港节点时在喜马拉雅官网也无法播放声音，想问一下你平时使用网页版有这种问题吗

**Comment by Diaoxiaozhang** [comment]
> 同样的问题 最新的版本 下载不了了

你也是不在国内吗

**Comment by anywugn** [comment]
我也遇到了同一个问题，我也是在海外，大概几个月前还能正常下载，今天发现不行了，尝试了0.3.2和最新版

**Comment by friskde** [comment]
国内一样遇到这问题

**Comment by Diaoxiaozhang** [comment]
我自己测试也发现了，疑似是喜马拉雅对网页版接口增加新的限制了，我最近比较忙，过两天有空了再解决

**Comment by guo-chuanchuan** [comment]
期待您早日解决，最近喜马拉雅的接口不像之前那么容易找到了

**Comment by Diaoxiaozhang** [comment]
已修复，请测试

**Comment by lovecn** [comment]
@Diaoxiaozhang 下载最新的Ximalaya-Downloader-v0.3.9.1.exe 提示
```js
Traceback (most recent call last):
  File "cli.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "main.py", line 22, in <module>
ModuleNotFoundError: No module named 'execjs'
[12532] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by Diaoxiaozhang** [comment]
> @Diaoxiaozhang 下载最新的Ximalaya-Downloader-v0.3.9.1.exe 提示
> 
> ```js
> Traceback (most recent call last):
>   File "cli.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "main.py", line 22, in <module>
> ModuleNotFoundError: No module named 'execjs'
> [12532] Failed to execute script 'cli' due to unhandled exception!
> ```

抱歉，翻了个低级错误，马上改😂

**Comment by Diaoxiaozhang** [comment]
> @Diaoxiaozhang 下载最新的Ximalaya-Downloader-v0.3.9.1.exe 提示
> 
> ```js
> Traceback (most recent call last):
>   File "cli.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "main.py", line 22, in <module>
> ModuleNotFoundError: No module named 'execjs'
> [12532] Failed to execute script 'cli' due to unhandled exception!
> ```

好了，重新传了，你再试下

**Comment by yanzhangshuai** [comment]
你好，我用的v4版本也是出现这个错误， 国内网络
![image](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/31086862/0d2a6594-83ba-4d3e-afc7-f634770157cc)
