### ISSUE TITLE
声音都无法下载

### ISSUE THREAD

**Issue by ftpc** [Diaoxiaozhang/Ximalaya-Downloader#57]
非VIP账号，第一次初始化，第一次配置，第一次打开，能解析专辑名，但不管是下载单个声音，还是整个专辑，都提示已达上线，不管是试听的声音还是免费的声音也是一样，都无法下载。

**Comment by iapeng** [comment]
刚才测试了，所有都不能下载了，期待楼主出手

**Comment by guo-chuanchuan** [comment]
有没有人找到新的接口了呀，求告知！！！

**Comment by iapeng** [comment]
源码中不是有个网址解密自定义函数，估计这个改了参数。应该写在某个js文件中吧

**Comment by Diaoxiaozhang** [comment]
已修复，请测试

**Comment by iapeng** [comment]
启动不了，闪退、

**Comment by HP-hhe** [comment]
貌似又不行了

**Comment by YYGXjpg** [comment]
请问现在的每日限制是多少？有没有人知道呢？
而且是不是不能用多线程下载？我昨天单线程下了500个之后改多线程就说上限了；但是今天一直单线程下了1800还在继续下
