### ISSUE TITLE
能否增加文稿下载功能

### ISSUE THREAD

**Issue by jinshuqishi2019** [Diaoxiaozhang/Ximalaya-Downloader#58]
如题，使用文稿更加方便阅读，麻烦作者考虑下增加文稿下载功能，谢谢。

**Comment by Diaoxiaozhang** [comment]
> > 如题，使用文稿更加方便阅读，麻烦作者考虑下增加文稿下载功能，谢谢。
> 
> 什么是文稿下载，喜马拉雅哪里有文稿

他说的应该是客户端ai生成的文稿，这个理论上是可以搞，但是我看了一下逆向有点难度

**Comment by aionyzq** [comment]
你可以上传到移动云，然后它支持AI转文稿。
