### ISSUE TITLE
第一次用，一直报错，麻烦看一下

### ISSUE THREAD

**Issue by tailangjun** [Diaoxiaozhang/Ximalaya-Downloader#61]
Traceback (most recent call last):
  File "/home/tailangjun/Share/AudioDownloader/Ximalaya-Downloader/cli.py", line 183, in <module>
    loop.run_until_complete(ximalaya.get_selected_sounds(sounds, album_name, start, end, headers, int(choice), number, path))
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tailangjun/Share/AudioDownloader/Ximalaya-Downloader/main.py", line 249, in get_selected_sounds
    sounds_info = await asyncio.gather(*tasks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tailangjun/Share/AudioDownloader/Ximalaya-Downloader/main.py", line 153, in async_analyze_sound
    sound_info[1] = self.decrypt_url(encrypted_url["url"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tailangjun/Share/AudioDownloader/Ximalaya-Downloader/main.py", line 285, in decrypt_url
    result = context.call("getSoundCryptLink", {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_external_runtime.py", line 85, in _exec_
    output = self._exec_with_tempfile(source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_external_runtime.py", line 127, in _exec_with_tempfile
    self._fail_on_non_zero_status(ret, stdoutdata, stderrdata)
  File "/opt/anaconda3/lib/python3.11/site-packages/execjs/_external_runtime.py", line 134, in _fail_on_non_zero_status
    raise ProcessExitedWithNonZeroStatus(status=status, stdout=stdoutdata, stderr=stderrdata)
execjs._exceptions.ProcessExitedWithNonZeroStatus: (101, '', 'Warning: The jjs tool is planned to be removed from a future JDK release\n/tmp/execjsoksz_o52.js:3:0 Expected an operand but found const\nconst r = new Uint8Array([188, 174, 178, 234, 171, 147, 70, 82, 76, 72, 192, 132, 60, 17, 30, 127, 184, 233, 48, 105, 38, 232, 240, 21, 47, 252, 41, 229, 209, 213, 71, 40, 63, 152, 156, 88, 51, 141, 139, 145, 133, 2, 160, 191, 11, 100, 10, 78, 253, 151, 42, 166, 92, 22, 185, 140, 164, 91, 194, 175, 239, 217, 177, 75, 19, 225, 94, 107, 125, 138, 242, 31, 182, 150, 15, 24, 226, 29, 80, 116, 168, 118, 28, 1, 186, 220, 158, 79, 59, 244, 119, 9, 189, 161, 74, 130, 221, 56, 216, 241, 212, 26, 218, 170, 85, 165, 153, 69, 238, 93, 255, 142, 3, 159, 215, 67, 33, 249, 53, 176, 77, 254, 222, 25, 115, 101, 148, 16, 13, 237, 197, 5, 58, 157, 135, 248, 223, 61, 198, 211, 110, 44, 54, 111, 52, 227, 4, 46, 205, 7, 219, 136, 14, 87, 114, 64, 104, 50, 39, 203, 81, 196, 43, 163, 173, 109, 108, 187, 102, 195, 37, 235, 65, 190, 113, 149, 143, 8, 27, 155, 207, 134, 123, 224, 129, 245, 62, 66, 172, 122, 126, 12, 162, 214, 90, 247, 251, 124, 201, 236, 117, 183, 73, 95, 89, 246, 181, 179, 83, 228, 193, 99, 6, 45, 112, 32, 154, 128, 230, 131, 206, 243, 57, 84, 146, 0, 35, 96, 250, 137, 36, 208, 103, 34, 68, 204, 231, 144, 120, 98, 202, 49, 210, 23, 200, 18, 86, 55, 121, 20, 199, 97, 167, 180, 169, 106])\n^\n/tmp/execjsoksz_o52.js:4:4 Expected an operand but found ,\n    ,\n    ^\n/tmp/execjsoksz_o52.js:16:0 Expected an operand but found const\nconst c = (e => {\n^\n/tmp/execjsoksz_o52.js:17:8 Expected an operand but found let\n        let t = {};\n        ^\n/tmp/execjsoksz_o52.js:18:33 Expected ) but found =>\n        return e.forEach(((e, r) => t[e] = r)),\n                                 ^\n/tmp/execjsoksz_o52.js:27:0 Expected an operand but found const\nconst f = i ? e => atob(e.replace(/[^A-Za-z0-9\\+\\/]/g, "")) : u ? t => e.from(t, "base64").toString("binary") : e => {\n^\n/tmp/execjsoksz_o52.js:32:12 Expected ; but found t\n        let t, r, n, o = "";\n            ^\n/tmp/execjsoksz_o52.js:33:17 Expected ; but found a\n        for (let a = 0; a < e.length;)\n                 ^\n/tmp/execjsoksz_o52.js:33:37 Expected ; but found )\n        for (let a = 0; a < e.length;)\n                                     ^\n/tmp/execjsoksz_o52.js:36:8 Invalid return statement\n        return o\n        ^\n/tmp/execjsoksz_o52.js:37:4 Expected eof but found }\n    }\n    ^\n')

**Comment by Diaoxiaozhang** [comment]
安装下nodejs

**Comment by Diaoxiaozhang** [comment]
不需要了，下载新版本使用

**Comment by tailangjun** [comment]
> 不需要了，下载新版本使用

意思是我更新一下代码就可以了，是吗？

**Comment by tailangjun** [comment]
更新后，可以下载了，下载还挺快，真不错
