### ISSUE TITLE
下载地址不能修改问题

### ISSUE THREAD

**Issue by cdd121** [Diaoxiaozhang/Ximalaya-Downloader#62]
0.3.9.1版本
win10系统

下载地址没法修改，修改下载地址后，无论是否登录，

打开程序，config.json自动被改回原状：{"cookie": "", "path": ""}

只登录，不修改下载地址，没有问题

**Comment by Diaoxiaozhang** [comment]
等我有空了看一下

**Comment by Diaoxiaozhang** [comment]
我测试时未发现同样的问题，你要不再试试？是不是哪里误操作了，对照readme里手动设置下载路径的方法再试试
