### ISSUE TITLE
下载单个是可以的，下载整个专辑，或者专辑的部分音频 都是下载失败

### ISSUE THREAD

**Issue by triumph** [Diaoxiaozhang/Ximalaya-Downloader#65]
下载单个是可以的，下载整个专辑，或者专辑的部分音频 都是下载失败？  4.0 版本

**Comment by Diaoxiaozhang** [comment]
提供具体报错内容、日志文件

**Comment by c469591** [comment]
作者大大好，我也遇到类似的问题，下载了93个之后后面的全部失败，专辑应该有1500多个文件，
不过我失败就关闭程序了，下面是第二次尝试下载的日治，似乎看不出什么来

[app.log](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/15476932/app.log)

之后再尝试下载整张专辑就直接失败了，一手兜下载不了
