### ISSUE TITLE
下载整个专辑问题

### ISSUE THREAD

**Issue by JunjieLl** [Diaoxiaozhang/Ximalaya-Downloader#67]
下载专辑时，有时候会遇到里面大部分音频无法下载，具体是指下载的文件打不开，大小在350字节（这些不能播放），偶尔会有几首能播放的，请问一下这个问题是？ 例如专辑id： 5999863

**Comment by Diaoxiaozhang** [comment]
不好意思啊，这个issue一直没有看到，我今天测试了一下，没有出现这种问题，你要不用最新版再测试一下？
