### ISSUE TITLE
建议添加音质选择功能

### ISSUE THREAD

**Issue by yinin6** [Diaoxiaozhang/Ximalaya-Downloader#7]
作者您好，一个小建议：
` def get_encrypted_url(self, sound_id, headers):`方法中，`trackQualityLevel`可以设置`1-3`，对应的`["playUrlList"][0]`为相应音质的`url`，指的注意的是，最高画质的音配文件后缀不是`.m4a`需要修改一下相应的保存代码。

**Comment by Diaoxiaozhang** [comment]
感谢反馈，之后会加入的！
