### ISSUE TITLE
输入音频链接或者id这一步后工具界面突然关闭

### ISSUE THREAD

**Issue by AlstonZhuang** [Diaoxiaozhang/Ximalaya-Downloader#70]
请教大佬，我几个月前用你的工具下载喜马拉雅的免费音频时一直是好的，然后前几天又试了一下，在输入音频网页链接或者id这一步后软件立马闪退，这是怎么回事呢？该怎么解决呢？谢谢

**Comment by Diaoxiaozhang** [comment]
用cmd运行不会闪退，把报错内容发过来

**Comment by AlstonZhuang** [comment]
大佬我明晚回去了运行给你看，我们可以加个微信交流吗？谢谢
![Uploading mmqrcode1720012483613.png…]()

**Comment by AlstonZhuang** [comment]
大佬，我的微信是18622931736
