### ISSUE TITLE
不能下载

### ISSUE THREAD

**Issue by bluepig001** [Diaoxiaozhang/Ximalaya-Downloader#72]
软件下载时提示：ID为741772546的声音解析失败，可能因为达到每日付费音频下载上限。
版本3.9.1 4.0
windows 10 11
已经有几天了，免费和付费都不行。
麻烦在百忙中偷闲处理一下，谢谢。

**Comment by Diaoxiaozhang** [comment]
请提供日志文件，我测试时没有发现问题

**Comment by bluepig001** [comment]
日志文件好像没什么问题。给您看看2个下载截图。
[app.log](https://github.com/user-attachments/files/16278730/app.log)
![屏幕截图 2024-07-18 142233](https://github.com/user-attachments/assets/8a5e3a87-b8a6-466e-be0a-d2e9a1ca9bb7)
![屏幕截图 2024-07-18 142359](https://github.com/user-attachments/assets/3341ce08-1008-463f-88ef-7172514cd78c)

**Comment by Diaoxiaozhang** [comment]
已经更新修复，请测试

**Comment by c469591** [comment]
我是非中國地區使用，選擇下載整張專輯都無法下載，日誌看起來也沒有問題，cli的輸出顯示我已經到達每日上限
[app.log](https://github.com/user-attachments/files/16341382/app.log)

**Comment by Diaoxiaozhang** [comment]
> 我是非中國地區使用，選擇下載整張專輯都無法下載，日誌看起來也沒有問題，cli的輸出顯示我已經到達每日上限 [app.log](https://github.com/user-attachments/files/16341382/app.log)

你把config文件删除重新登录一下再试一下

**Comment by c469591** [comment]
可以了，謝謝!
