### ISSUE TITLE
目前下载免费音频下载不了了

### ISSUE THREAD

**Issue by maple0308** [Diaoxiaozhang/Ximalaya-Downloader#73]
大佬，您好，最近在使用下载免费专辑的过程中，出现了下载不了的情况，当天没有下载的情况下解析失败，可能因为达到每日付费音频下载上线，这个是没有下载一个音频的情况下出现的请款，麻烦大佬看一下这种情况是什么问题。
[app.log](https://github.com/user-attachments/files/16272960/app.log)

**Comment by maple0308** [comment]
第一个日志文件上传错了，这个才是正确的，里面有解析失败的内容
[app.log](https://github.com/user-attachments/files/16276475/app.log)
[app.log](https://github.com/user-attachments/files/16276472/app.log)

**Comment by maple0308** [comment]
![92a8ff30-1f3d-46ff-8c66-10caa4ecf14d](https://github.com/user-attachments/assets/0fd597d0-d9ff-4ff6-a951-c3d48378f8eb)

**Comment by Diaoxiaozhang** [comment]
已经更新修复，请测试

**Comment by maple0308** [comment]
![1721699698243](https://github.com/user-attachments/assets/1cc136b0-a7a3-45a6-b0cd-b45751de8b47)
还是不行，提示已达上限。

**Comment by maple0308** [comment]
![image](https://github.com/user-attachments/assets/2ebf3e06-6414-4e12-84b3-cb7dad3b2ef4)
还是不行，跟之前一样的情况。
[app.log](https://github.com/user-attachments/files/16343498/app.log)

**Comment by Diaoxiaozhang** [comment]
> ![image](https://private-user-images.githubusercontent.com/168344751/351177531-2ebf3e06-6414-4e12-84b3-cb7dad3b2ef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTgzNjcsIm5iZiI6MTcyMTcxODA2NywicGF0aCI6Ii8xNjgzNDQ3NTEvMzUxMTc3NTMxLTJlYmYzZTA2LTY0MTQtNGUxMi04NGIzLWNiN2RhZDNiMmVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNzAxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2JiYzE2ZGMyMTRkOWVkOTAyYmNkMTlmNzkzNjllYzU2NDI5ZmZkMDE5MzczYjVjMTI1M2Q3Yzc2ZDBjOGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mvzsGzH2I15CbUWboq5Shfnn6eimM2vw7Sa3Zf0kXc0) 还是不行，跟之前一样的情况。 [app.log](https://github.com/user-attachments/files/16343498/app.log)

把config文件删除重新登录一下再试，忘记说了

**Comment by joker-ride** [comment]
#72 
@Diaoxiaozhang 你好我下载的是免费的音频，依旧不能下载

**Comment by maple0308** [comment]
![image](https://github.com/user-attachments/assets/49279b1b-0a8a-4158-9b32-50057a0ffcb3)
想下载一个军事博客的音频，用登录的情况下还是提示这个，在很早之前用这个没有登录的情况下，是可以下载博客的音频，但是现在登录情况下，下载不了博客的音频了，是因为音频数量太多了吗？

**Comment by maple0308** [comment]
[app.log](https://github.com/user-attachments/files/16360360/app.log)
这个是博客下载失败的日志，麻烦您看一下。

**Comment by Diaoxiaozhang** [comment]
> #72 
> @Diaoxiaozhang 你好我在不登陆的情况下，依旧不能下载免费的音频。我看您说的，我试了下如果登录的话，倒是可以下载。我想问下要如何才能实现不登陆，也能下载免费的音频呢？
> 

我在网页端测试了下，现在不登录账号下载需要滑块验证，要在这个程序实现不登陆下载会很复杂了，所以还是登录账号下载吧

**Comment by Diaoxiaozhang** [comment]
> ![image](https://github.com/user-attachments/assets/49279b1b-0a8a-4158-9b32-50057a0ffcb3)
> 想下载一个军事博客的音频，用登录的情况下还是提示这个，在很早之前用这个没有登录的情况下，是可以下载博客的音频，但是现在登录情况下，下载不了博客的音频了，是因为音频数量太多了吗？

我测试了一下，出现这个问题是因为音频接口中本应该是音质的变量在博客这里变成了ai配音的音色，我有空会修复的

**Comment by maple0308** [comment]
目前登录状态下只能下载500个音频以内的专辑，超过500个音频的专辑，直接提示下载失败应该是喜马拉雅限制了账号下载的数量。

**Comment by Diaoxiaozhang** [comment]
> 目前登录状态下只能下载500个音频以内的专辑，超过500个音频的专辑，直接提示下载失败应该是喜马拉雅限制了账号下载的数量。

貌似确实是这样，暂时也没办法了

**Comment by joker-ride** [comment]
> > #72
> > @Diaoxiaozhang 你好我在不登陆的情况下，依旧不能下载免费的音频。我看您说的，我试了下如果登录的话，倒是可以下载。我想问下要如何才能实现不登陆，也能下载免费的音频呢？
> 
> 我在网页端测试了下，现在不登录账号下载需要滑块验证，要在这个程序实现不登陆下载会很复杂了，所以还是登录账号下载吧

感谢大佬
