### ISSUE TITLE
使用最新版本依然无法下载免费音频

### ISSUE THREAD

**Issue by Dengben142** [Diaoxiaozhang/Ximalaya-Downloader#75]
下载的最新版本依然无法下载，使用了前一个版本也是这样，也删过config重新登陆还是一样。请老哥讲一下如何操作，麻烦啦
[app.log](https://github.com/user-attachments/files/16388983/app.log)
![d01227d7d6819b20b3ad8157c3028e7](https://github.com/user-attachments/assets/dd5f50f3-6fba-4d4c-bbc3-fe44d026b47d)

**Comment by Diaoxiaozhang** [comment]
建议你明天再试一下，这次可能真是到达上限了，现在限制又变更严了

**Comment by Dengben142** [comment]
好的  那我明天再试一下，谢谢大佬。这个每天下载限制是和系统总的下载量有关吗？我今天一个没有下载😂😂

**Comment by Diaoxiaozhang** [comment]
具体的我也不清楚
