### ISSUE TITLE
部分声音下载失败

### ISSUE THREAD

**Issue by 10zhou** [Diaoxiaozhang/Ximalaya-Downloader#76]
专辑声音为3290982，报错和日志如下：
![image](https://github.com/user-attachments/assets/aad42ea2-751d-4a9b-8d68-8046c1a49474)
![image](https://github.com/user-attachments/assets/280aaa52-daee-4730-bb13-adbc444ea4b8)

**Comment by Diaoxiaozhang** [comment]
你再测试一下，现在好像正常了
