### ISSUE TITLE
下载文件加序号命名问题以及下载专辑部分下载不下来的问题

### ISSUE THREAD

**Issue by yuzhongchentu** [Diaoxiaozhang/Ximalaya-Downloader#77]
针对v0.4.2 版本
1、下载的文件多了，文件命名就会出现不同的情况，下载的时候选择的是加序号，加序号后边就是专辑名，但是会出现专辑名不全，或者是一个文件名的序号出现两遍或三遍（例如：2056-2056-2056 XXXX或者是2046-2046 XXXX），其中两遍的概率比较高，三遍的概率较两遍的比较低，正常编号的命名文件比较少，我下载了一个接近3000集的专辑，序号错误（序号重复）的文件大约有4/5。

2、还有就是下载不下来的时候，提示该账号当日文件下载的数量达到上限，但是我用新开的新号开会员登陆后下载同一个专辑还会出现相同的情况。

**Comment by Diaoxiaozhang** [comment]
你测试一下，现在好像正常了

**Comment by 10zhou** [comment]
这个问题我也遇到了，不过用正则表达式批量重命名也很方便：

你可以使用PowerRename工具中的正则表达式功能来修复这些重复的序号。以下是一个合适的正则表达式及其替换方式：

正则表达式：
```
(\d{3})-\1-(.*)
```

替换为：
```
$1-$2
```

解释：
- `(\d{3})`：匹配并捕获三个连续的数字。
- `-\1-`：匹配一个破折号，紧接着是前面捕获的相同的三个数字，再接一个破折号。
- `(.*)`：匹配并捕获剩下的任何字符（即标题部分）。

替换部分：
- `$1`：第一个捕获组，即第一个序号。
- `-$2`：破折号和第二个捕获组，即标题部分。

这样，重复的序号将被移除，留下正确的格式。

在PowerRename工具中，你可以这样设置：
1. 在“Search for”框中输入上述正则表达式。
2. 在“Replace with”框中输入替换格式。
3. 勾选“Use Regular Expressions”选项。

完成设置后，应用更改即可修复这些重复的序号。
