### ISSUE TITLE
当前软件已经失效，没法正常下载了。

### ISSUE THREAD

**Issue by HanLuo** [Diaoxiaozhang/Ximalaya-Downloader#80]
当前软件已经失效，没法正常下载。输入专辑ID返回了空的信息。

![QQ截图20240824182045](https://github.com/user-attachments/assets/0be30a20-ea8a-4ebf-bb42-a3ff670c8692)

**Comment by Diaoxiaozhang** [comment]
我测试后没有发现这样的问题，你这情况有点奇怪，一般不太可能在这一步就出错的，你在浏览器上能正常播放吗

**Comment by HanLuo** [comment]
在浏览器上面是正常播放的。

**Comment by Diaoxiaozhang** [comment]
你有改过代码吗？我看这data里的pagesize怎么是0，本应该是100，你直接用我打包好的exe试试？

**Comment by jakecodespace** [comment]
我这里也有同样的问题，打包好的exe也不行。似乎是被反爬了？

![ima？ge](https://github.com/user-attachments/assets/b86d312c-efed-434f-af73-dea5a26335d0)

**Comment by jakecodespace** [comment]
已解决：需要在headers头中加入headers["xm - sign"]参数
![image](https://github.com/user-attachments/assets/058de639-a793-4ac4-b60f-dbe37b44d3fb)

**Comment by Diaoxiaozhang** [comment]
已修复，不过貌似有点治标不治本），它应该是有个新的反爬措施，很奇怪，第一次请求会出错但多试几次就行，等我有空再研究研究

**Comment by jakecodespace** [comment]
感谢大佬！！！！！想请问一下这个反爬是什么原理。刚入门爬虫，还望大佬不吝赐教！还有一个小问题是比如专辑id：55935825。在网站里是有157个声音，都能正常播放。但是这里爬取只能获得145个声音。

**Comment by Diaoxiaozhang** [comment]
> 感谢大佬！！！！！想请问一下这个新的反爬是什么原理。刚入门爬虫，还望大佬不吝赐教！

我目前也不太清楚

**Comment by HanLuo** [comment]
我对爬虫这一块，也不是很熟悉。我摸索了一下，好像是有个验证码，但是在浏览器上面，没有这个验证码。

**Comment by Diaoxiaozhang** [comment]
修复好了，喜马拉雅这次应该只是将获取专辑音频目录信息的请求改为也需要cookie了，以前的版本中发送这个请求都是不带cookie的，前两天多重试几次就会成功应该只是喜马拉雅的bug
