### ISSUE TITLE
不能正常启动

### ISSUE THREAD

**Issue by 006s** [Diaoxiaozhang/Ximalaya-Downloader#81]
![QQ_1724567561278](https://github.com/user-attachments/assets/de7856b5-f72c-4d4f-90e0-ed4dd6cb0fb8)
更新了了依赖，之前0.4版本还能正常使用，刚更新完毕，打不开了，报错附上图

**Comment by Diaoxiaozhang** [comment]
更新了，貌似github的api有点问题，先取消了检测版本更新的功能，等我再研究研究

**Comment by 006s** [comment]
选择用浏览器登录也有bug，无法正常启动，报错退出

**Comment by Diaoxiaozhang** [comment]
发一下日志

**Comment by 006s** [comment]
![QQ_1724580651227](https://github.com/user-attachments/assets/30c51efe-17fb-4f03-8275-301520594ee8)
app.log无输出

**Comment by Diaoxiaozhang** [comment]
你先手动输入cookie吧，看你这个报错只能知道应该是webdriver manager出的问题，具体原因不太清楚，我这边也无法复现

**Comment by 006s** [comment]
嗯，其他一切正常，有问题我再反馈
