### ISSUE TITLE
登陆后输入专辑id无法解析

### ISSUE THREAD

**Issue by yosaku01** [Diaoxiaozhang/Ximalaya-Downloader#82]
一直停在解析阶段

**Comment by Diaoxiaozhang** [comment]
已修复

**Comment by yosaku01** [comment]
> 已修复
谢谢，我回家试一下

**Comment by jdnx** [comment]
@yosaku01  现在还能用吗? 看修改是加了header,好像现在加了也不返回信息了?

**Comment by Diaoxiaozhang** [comment]
> @Diaoxiaozhang 现在还能用吗? 看修改是加了header,好像现在加了也不返回信息了?

你遇到什么问题了吗，我这边测试还是正常可用的。

**Comment by jdnx** [comment]
> > @Diaoxiaozhang 现在还能用吗? 看修改是加了header,好像现在加了也不返回信息了?
> 
> 你遇到什么问题了吗，我这边测试还是正常可用的。

感谢回复, 我自己抓包看了下, getalbum是可以返回数据的, 但是不是光 1&_token  设置这一个cookie已经不行了, 用之前我自己写过的代码是只设置这一个cookie的, 貌似就返回空数据了
